name: guidey
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.5
  url_launcher: ^6.3.0
  shared_preferences: ^2.0.0
  font_awesome_flutter: ^10.7.0
  dash_chat_2: ^0.0.21
  chat_gpt_sdk: ^3.1.5
  intl: 0.20.2
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  http: ^1.1.0
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  intl: 0.20.2

flutter:
  uses-material-design: true
  assets:
    - assets/